[package]
name = "kernel"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies]
# Add any kernel-specific dependencies

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"