[build]
target = "aarch64-unknown-none.json"

[unstable]
build-std = ["core"]

[target.aarch64-unknown-none]
linker = "aarch64-none-elf-ld"
rustflags = [
    "-C", "no-prepopulate-passes",
    "-C", "panic=abort",
    "-Z", "ub-checks=false",
    "-C", "no-redzone",
    "-C", "force-frame-pointers=no",
    "-C", "link-arg=-Tlinker.ld",
    "-A", "missing_abi"
]